### ISSUE TITLE
由于华为mate60后续的机型不再对安卓层透出基站信息，会导致高德仅基站定位时，频繁触发定位失败的情况。

### ISSUE THREAD

**Issue by justdoitgo** [Wayaer/fl_amap#10]
特殊原因：
由于华为mate60后续的机型不再对安卓层透出基站信息，会导致高德仅基站定位时，频繁触发定位失败的情况。
解决方式：
1.等待高德后续版本修复
2.如果时间有要求，可以使用华为提供解决方式，接入华为系统定位。

参数设置 应该怎么设置

**Comment by Wayaer** [comment]
`AMapLocationOptionForAndroid( gpsFirst: true,)`

**Comment by justdoitgo** [comment]
谢谢！
