### ISSUE TITLE
安卓 fl_amap_map Execution failed for task ':fl_amap_map:compileDebugKotlin'.

### ISSUE THREAD

**Issue by imWalsh** [Wayaer/fl_amap#14]
e: file:///Users/Desktop/flutter_app/fl_amap_map/android/src/main/kotlin/fl/amap/map/AMapMapPlugin.kt:44:42 Type mismatch: inferred type is BinaryMessenger but String was expected
e: file:///Users/Desktop/flutter_app/fl_amap_map/android/src/main/kotlin/fl/amap/map/AMapMapPlugin.kt:44:59 Type mismatch: inferred type is String but BinaryMessenger was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fl_amap_map:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

看了下 是 flMapViewEvent = FlEvent("fl_amap_map/event", binaryMessenger)

两个参数的位置 写反了，但是 在页面退出的时候 

@override
  void dispose() {
    // _aMapController?.dispose();
    super.dispose();
  }

调用 _aMapController?.dispose();  就会报错 闪退

**Comment by Wayaer** [comment]
已修复更新
