### ISSUE TITLE
ios 初始化失败

### ISSUE THREAD

**Issue by NiBoTe** [Wayaer/fl_amap#3]

**Comment by NiBoTe** [comment]
final bool data = await FlAMapLocation().initialize(AMapLocationOption(
        gpsFirst: true
    ));
    if (data) {
      print('初始化成功');
    }

返回 flase.

**Comment by Wayaer** [comment]
不会吧。你有看example的代码么？

**Comment by NiBoTe** [comment]
看了呢， android是好的

**Comment by Wayaer** [comment]
有没有报错信息，贴出来看看！或者你用xcode运行一次，看看有没有报错信息

**Comment by Wayaer** [comment]
![image](https://user-images.githubusercontent.com/17231965/144960541-756a528f-a42c-4be7-8055-da7c68de8f2d.png)
我在iphone7p 上测试的没问题，可能你需要更新一下ios的依赖库，`cd  ios`  && `pod update`
