### ISSUE TITLE
3.0版本获取getLocation速度很慢

### ISSUE THREAD

**Issue by ibaoyun** [Wayaer/fl_amap#8]
上一个版本，getLocation获取位置时，同时返回逆地址信息，很快。
这个版本需要指定选项相关值为true才返回逆地址信息，且速度太慢，使用体验不好。

**Comment by Wayaer** [comment]
android还是ios?

**Comment by lxj916904395** [comment]
我的getLocation 返回定位iOS很慢，Android很快

**Comment by ibaoyun** [comment]
> android还是ios?

iOS的

**Comment by ibaoyun** [comment]
回退到2.5先用着

**Comment by Wayaer** [comment]
是因为3.0 默认为米级定位，上个版本默认是十米级，重新发了版本可以更新下
